# The following Environment Variables should be set in GitLab.
# OpenShift:
#       OPENSHIFT_TOKEN = Go to OpenShift Console, under Resources select Secrets, click Create Secret button, this will create a login Token
# Azure:
#       AZURE_DEPLOY_USERNAME = Go to Azure Portal, open your App, enter a username and password under the Deployment Credentials menu
#       AZURE_DEPLOY_PASSWORD = See above
# Google:
#       GOOGLE_TOKEN = Go to Google Console, open your App, go to IAM & admin menu, create a Service Account for GitLab, export the JSON key
# Heroku:
#       HEROKU_TOKEN = Go to Heroku CLI, login, run the command heroku auth:token
#

deploy_openshift:
    image: openshift/origin-cli
    stage: deploy
    environment: openshift
    only:
        - master
    script:
        - echo "Deploying for OpenShift Cloud Platform"
        - oc login --token=$OPENSHIFT_TOKEN https://console.starter-ca-central-1.openshift.com
        - oc start-build cloudapp
        - oc logout
    when: manual

deploy_azure:
    image: centos
    stage: deploy
    environment: azure
    only:
        - master
    script:
        - echo "Deploying for Azure Cloud Platform"
        - sed -i 's/^APP_ENV=.*/APP_ENV=azure/' .env
        - yum install zip -y
        - /usr/bin/zip -r cloudapp.zip .
        - curl -X POST -u $AZURE_DEPLOY_USERNAME:$AZURE_DEPLOY_PASSWORD --data-binary @"cloudapp.zip" https://markwsapp.scm.azurewebsites.net/api/ZipDeploy
    when: manual

deploy_google:
    image: google/cloud-sdk
    stage: deploy
    environment: google
    only:
        - master
    script:
        - echo "Deploying for Google Cloud Platform"
        - echo $GOOGLE_TOKEN > /tmp/$CI_PIPELINE_ID.json
        - sed -i 's/^APP_ENV=.*/APP_ENV=google/' .env
        - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
        - gcloud --quiet --project cloud-workshop-207715 app deploy
    after_script:
        - rm /tmp/$CI_PIPELINE_ID.json
    when: manual
    
deploy_heroku:
    image: centos
    stage: deploy
    environment: heroku
    only:
        - master
    script:
        - echo "Deploying for Heroku Cloud Platform"
        - sed -i 's/^APP_ENV=.*/APP_ENV=heroku/' .env
        - yum install git -y
        - git remote add heroku https://heroku:$HEROKU_TOKEN@git.heroku.com/mark-cloudapp.git
        - git config --global user.email "markreha@mac.com"
        - git config --global user.name "Mark Reha"
        - git config --global push.default matching
        - git add -A
        - git status
        - git commit -m "Release from GitLab"
        - git push -f heroku HEAD:master
    when: manual
