image: google/cloud-sdk

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

deploy_production:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy
