variables:
  - CLOUD_PLATFORM="google"

deploy_google:
  image: google/cloud-sdk
  stage: deploy
  environment: $CLOUD_PLATFORM
  only:
    - master
  script:
    - echo "Deploying for Google Cloud Platform"
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json
