version: 0.2

phases:
    build:
        commands:
            - echo 'In My Build............'
            - sed -i 's/^APP_ENV=.*/APP_ENV=openshift/' .env
    post_build:	
        commands:
            - echo 'In My Post Build.......'
            - printf '[{"name":"first-run-task-definition","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
            - cat imagedefinitions.json
        
artifacts:
    files: imagedefinitions.json
